package com.equalizerapo.android.model

/**
 * Representation of an Equalizer APO preset configuration file (e.g. config.txt / Peace GUI config).
 */
data class ApoPreset(
    val name: String,
    var preampDb: Float = 0.0f,
    val filters: MutableList<EqFilter> = mutableListOf()
) {
    /**
     * Generate full Equalizer APO compatible text file output.
     */
    fun exportToText(): String {
        val sb = StringBuilder()
        sb.append("# Equalizer APO Config generated by Equalizer APO Android\n")
        sb.append("Preamp: ${if (preampDb >= 0) "+" else ""}${String.format("%.2f", preampDb)} dB\n\n")
        
        filters.forEachIndexed { index, filter ->
            filter.id = index + 1
            sb.append(filter.toApoSyntax()).append("\n")
        }
        return sb.toString()
    }
}
